language: php

git:
  depth: 5

matrix:
  include:
    - php: 5.5
      dist: trusty
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4snapshot

install:
  - travis_retry composer self-update
  - travis_retry composer install

script:
  - vendor/bin/phug-dev check --report --coverage-php-version=5.6

notifications:
  slack: phug:nzXFnxhU14RWK2EQSDL0u08z

addons:
  code_climate:
    repo_token: 51c4d2fc70d816c3206e22a97f6c4d50cff4fe9dab77cd38c24742e6b2273696
